import { Link } from "react-router-dom";
import { Layout } from "../components/Layout";
import "../assets/style/LegalPage.css";

const policySections = [
  ["Information we collect", "We collect information you provide when you schedule a pickup, create an account, contact our team, or use our services. This may include your name, phone number, email address, pickup and delivery address, order preferences, and communication history. We may also collect limited technical information such as device, browser, and usage data to keep our website secure and reliable."],
  ["How we use your information", "ExcelCare uses your information to arrange pickups and deliveries, process and manage orders, respond to questions, improve our services, prevent misuse, and send important service updates. With your permission, we may also share relevant offers and service information. We do not sell your personal information."],
  ["Sharing and service partners", "We share information only when needed to deliver the service you request—for example, with pickup and delivery personnel, payment providers, technology partners, or where required by law. Our partners are expected to protect the information they receive and use it only for the agreed service purpose."],
  ["Data security and retention", "We use reasonable administrative, technical, and operational safeguards to protect personal information. No online system can guarantee absolute security, so please use care when sharing information. We retain information only for as long as necessary for service delivery, legal obligations, dispute resolution, and legitimate business records."],
  ["Your choices", "You may request access to, correction of, or deletion of the personal information we hold about you, subject to applicable law and operational requirements. You can also opt out of promotional communications at any time by using the unsubscribe option or contacting our support team."],
  ["Cookies and analytics", "Our website may use cookies and similar technologies to remember preferences, understand site performance, and improve your experience. You can control cookies through your browser settings; however, some website features may not work as intended if cookies are disabled."],
  ["Children's privacy", "ExcelCare services are not intended for children to use independently. We do not knowingly collect personal information from children without appropriate consent. If you believe a child has provided us information, please contact us so we can review and address the request."],
  ["Updates to this policy", "We may update this Privacy Policy as our services, technology, or legal obligations change. The latest version will always be posted on this page with its effective date. Continued use of ExcelCare after an update means you accept the revised policy."],
];

const termsSections = [
  ["Service scope", "ExcelCare provides laundry, dry cleaning, ironing, shoe care, curtain cleaning, carpet cleaning, and related doorstep services subject to availability in your location. A confirmed order may depend on item inspection, serviceability, pickup availability, and the care instructions applicable to each item."],
  ["Orders, pricing, and payment", "Prices, turnaround times, and available services may vary by item, location, treatment required, and order volume. Any estimate provided before inspection may be revised where additional treatment or specialist care is required. Payment must be completed according to the method and schedule communicated for your order."],
  ["Pickup and delivery", "Please ensure items are ready at the agreed pickup time and provide an accurate address and contact number. We will take reasonable care during pickup and delivery; however, delays caused by unavailable customers, incorrect details, weather, traffic, safety concerns, or events outside our control may affect schedules."],
  ["Garment and item care", "Customers should check pockets and remove cash, valuables, jewellery, keys, documents, and other personal items before handing over an order. Please disclose stains, damage, special instructions, and material details where known. Our team follows reasonable care processes, but results may vary based on fabric condition, prior damage, colour fastness, stains, and manufacturer care labels."],
  ["Claims and limitations", "Please inspect your order at delivery and report concerns promptly with relevant order details and photographs where possible. ExcelCare will review eligible claims fairly under its service process. Liability, where applicable, is limited to the affected service or item and does not cover inherent fabric defects, undisclosed conditions, normal wear, colour loss, shrinkage, or damage arising from unsuitable care labels or customer instructions."],
  ["Cancellations and refunds", "Cancellation and refund eligibility depends on the stage of your order and the service already performed. Once specialist treatment or cleaning has begun, cancellation may not be possible. Where a refund or re-service is approved, it will be processed using the appropriate method after review."],
  ["Website use", "You agree to use this website lawfully and not interfere with its security, availability, or other users. Content, branding, design, and materials on this site belong to ExcelCare or its licensors and may not be copied, modified, or used commercially without written permission."],
  ["Governing terms", "These Terms are governed by applicable laws in India. If a dispute arises, we encourage you to contact our support team first so we can seek a practical resolution. Any legal proceeding will be subject to the jurisdiction applicable to ExcelCare's registered operations."],
];

export function LegalPage({ type }) {
  const isPrivacy = type === "privacy";
  const title = isPrivacy ? "Privacy Policy" : "Terms & Conditions";
  const intro = isPrivacy ? "Your trust matters to us. This policy explains how ExcelCare collects, uses, and protects your information while delivering thoughtful fabric care." : "These terms explain how ExcelCare services, orders, pickups, and website use work—so every experience is clear, fair, and dependable.";
  const sections = isPrivacy ? policySections : termsSections;
  return <Layout><main className="legal-page">
    <section className="legal-page__hero"><div><p>EXCELCARE · CUSTOMER CARE</p><h1>{title}</h1><span>Effective date: September 9, 2026</span><p>{intro}</p></div></section>
    <section className="legal-page__body"><aside><b>On this page</b>{sections.map(([heading], index) => <a href={`#section-${index}`} key={heading}>{index + 1}. {heading}</a>)}<Link to="/contact-us">Need help? Contact us →</Link></aside><article><div className="legal-page__notice"><span>✦</span><p>We believe premium service starts with clarity. Please read this page carefully and contact us if you have any questions.</p></div>{sections.map(([heading, content], index) => <section id={`section-${index}`} key={heading}><span>{String(index + 1).padStart(2, "0")}</span><div><h2>{heading}</h2><p>{content}</p></div></section>)}<div className="legal-page__contact"><h2>Questions about {title.toLowerCase()}?</h2><p>Our support team is happy to help with any concern about your account, order, or information.</p><Link to="/contact-us">Contact ExcelCare →</Link></div></article></section>
  </main></Layout>;
}
